### ISSUE TITLE
Change font size

### ISSUE THREAD

**Issue by CooperBarrett** [koca/grav-theme-masonry#21]
Good morning,
I am a beginner in setting up a site.
I installed the Masonry theme only I'd like to change the font size. 
I understand it's in a CSS file but I don't see where to go at all...
If someone could help me, I'd be grateful.
thank you in advance.

**Comment by koca** [comment]
Hi there.
Could you be more spesific? You want to change font size of an element or whole page content?

**Comment by CooperBarrett** [comment]
So I'd like to change the font size of all my posts.

**Comment by koca** [comment]
The easiest way would be overriding the current css. So if you want to change the font size of post content, you could add the following css:
```css
.post-content{
  font-size: 1.2rem!important;
}
```
to your theme and the font size will be smaller in this case.

**Comment by CooperBarrett** [comment]
Perfect, thanks so much for your help.
I close and mark in resolved
