### ISSUE TITLE
Translations for e.g. "read more"

### ISSUE THREAD

**Issue by k1ngf15h3r** [koca/grav-theme-masonry#4]
Is there a possibility to handle text section like "read more" in multilingual ways?

**Comment by koca** [comment]
Yes, you can check the Cacti Theme https://github.com/getgrav/grav-theme-cacti it is multilangual.

**Comment by k1ngf15h3r** [comment]
added `READ_MORE: 'Weiterlesen'` to `system/languages/de.yaml`

changed Line 11 in `user/themes/masonry/templates/partials/article.html.twig` to:
```
<p>{{ post.content | striptags | truncate(140) }} <a class="read-more" href="{{post.url}}">{{ 'READ_MORE' | t }}</a></p>
```
after this I got the read more text section translated

**Comment by k1ngf15h3r** [comment]
this solutions also works for "older post" and "newer post". but the changes must be done in the themes twig files so I try to find a solution to make it working for further updates

**Comment by k1ngf15h3r** [comment]
can you tell me where "you might enjoy" text is comming from?

**Comment by koca** [comment]
@k1ngf15h3r its coming from [there](https://github.com/koca/grav-theme-masonry/blob/d581e567cc1727b98ac889d91300655da4b822ac/src/scss/screen.scss#L1359).

**Comment by k1ngf15h3r** [comment]
Okay this is a little bit tricky to translate permanently even if theme is
updated. Will look at this after my holiday.

Am 14.08.2016 00:10 schrieb "Mesut" <notifications@github.com>:
