### ISSUE TITLE
Pagination for newer post

### ISSUE THREAD

**Issue by k1ngf15h3r** [koca/grav-theme-masonry#5]
Pagination for newer posts is display left align and not centered. Any ideas to fix this?

**Comment by koca** [comment]
@k1ngf15h3r can you send me a screenshot?

**Comment by k1ngf15h3r** [comment]
The attached picture. Newer post is too much left side I think.

Am 14.08.2016 00:11 schrieb "Mesut" <notifications@github.com>:

**Comment by koca** [comment]
Any updates? I'll close for now ^^
