### ISSUE TITLE
header author

### ISSUE THREAD

**Issue by BennyBolivar** [koca/grav-theme-masonry#6]
Maybe you can use the theme-variable {{ page.header.author }} to display the author?

Sincerely Benny

**Comment by koca** [comment]
Hey benny,
Maybe, Kinda busy right now but feel free to send a PR :)

**Comment by BennyBolivar** [comment]
Sorry but i dont know how to do this :D I edited post.html.twig and would attach it here if this is ok.
PS: I added support for the comment-plugin, i hope this is ok :D 
Thanks for your work, i appre
[post.html.twig.zip](https://github.com/koca/grav-theme-masonry/files/581528/post.html.twig.zip)
ciate it a lot :)
